library(forecast)
library(fpp)
View(euretail)
auto.arima(euretail)
arima(euretail)
plot(euretail, ylab="Retail", xlab="year")
tsdisplay(diff(euretail,4))
fit <- Arima(euretail, order=c(0,1,1), seasonal=c(0,1,1))
tsdisplay(residuals(fit))
fit3 <- Arima(euretail, order=c(0,1,3), seasonal=c(0,1,1))
res <- residuals(fit3)
tsdisplay(res)
Box.test(res, lag=16, fitdf=4, type="Ljung")
plot(forecast(fit3, h=12))
